hamalsolutions/little-belies-widget

- package-lock.json
- src/App.js
Updating the /api/book/client requests for sending aditional information about the incomplete booking process
> Booked data

- yarn.lock
Package and yarn update for deployment
> updates for deployment

- src/App.js
> adding endpoint sendMail

- src/App.css
- src/App.js
- src/styles/info.css
- adding selector that lists the addons
- show info of each addons
- adding step progress
> Selector addons

- src/App.css
- src/App.js
- src/styles/info.css
fix Cannot find module: 'rsuite/dist/rsuite.css'
> Fix selector addons

- src/App.js
> Fix selector addonss

- src/App.js
- src/styles/info.css
adding 8k Realistic View option in AddOns selector
> Adding add ons 8k

- src/styles/info.css
- static change: 
adapting addons info card position for the widget
> adapting addons info card position for the widget

- src/App.js
> show-addons-when-booking

- src/App.js
- Remove Coral Spring's massage service
- Add description of the selected addons
- Validate the existence of the addons to send to payload
> Remove coral massage service

- src/App.js
add service prices cleveland hard code
> add service prices cleveland

- src/App.css
- src/App.js
add more width of addon information modals
> add more width addons info modals

- src/App.js
filtering sites dynamically, version 2
> filtering sites dynamically v2

- src/App.js
filtering services by seeOnLine v3
> filtering services by seeOnLine v3

- src/App.js
> Filtering services by see on line v3 optimized

- src/App.js
> Filtering services by see on line v4 optimized

- src/App.js
Reverts hamalsolutions/little-belies-widget#65
> Revert "Filtering services by see on line v3 optimized"

- src/App.js
- fix dynamic cost of services
> fix cost diynamical

- src/App.js
- filtering services by corals: Special Promo
> filtering services by corals

- src/App.js
- optimizing processes in the code
> optimized code

- src/App.js
> Filtering services massages

- src/App.js
send programId to /api/dynamoDB/appointments
> send programId /api/dynamoDB/appointments

- src/App.js
- sending language attribute to /book/client endpoint
> Send language book clients

- src/App.js
- getting the timeZone and sending it in the bookDate
> getting the timeZone and sending it in the bookDate

- src/App.js
- Change positon endpoint call
- send ProgramId to endpoint /api/dynamoDB/appointments
> change position endpoint call

- src/App.js
- validating scheduling availability depending on local time
- validate if there is an appointment scheduled at 10:00 am
- filter scheduling availability
> validating scheduling availability depending on local time

- src/App.js
> change StartDateTime to startDateTime

- src/App.js
> console.log localTime

- src/App.js
- changing local time on server
> change localTime server

- src/App.js
> change local Date

- src/App.js
Reverts hamalsolutions/little-belies-widget#84
> Revert "change local Date"

- src/App.js
Reverts hamalsolutions/little-belies-widget#83
> Revert "change localTime server"

- src/App.js
- tests with validation of 2 hours
> first test

- src/App.js
Reverts hamalsolutions/little-belies-widget#88
> Revert "first test"

- src/App.js
- validating available blocks against scheduled appointments
> validation of available blocks

- src/App.js
> validating additional cases

- src/App.js
- validate unavailabilities blocks
> validate unavailabilities blocks

- src/App.js
- validation of the first two hours in the schedule
> Validate two hours

- package-lock.json
- package.json
- src/App.js
- validate if there is more than one room
> Validate rooms and schedules

- src/App.js
- show from thursday if it is washington
> show from thursday if it is washington

- src/App.js
- if the day is greater than friday in washington
> if day is greater than friday in washington

- src/components/boookAppointment.js
> send attribute clientName

- src/App.js
- show availability from March 31, 2023 for site phoenix
> show availability from March 31, 2023

- src/App.js
Se dejo comentado el codigo de phoenix
> Codigo de apertura phoenix

- package.json
- src/App.js
- src/components/boookAppointment.js
- src/config/constans.js
Se quito lo de la apertura de phoenix.. Se dejo en comentario el codigo
> Release 0.1.7

- src/App.js
Se agrego una variable hourRestric para manejar con esa la restriccion de las horas al inicio del dia en el sitio si no hay citas agendadas
> Cambiando hora de restriccion

- src/App.js
Estaba en 2 la hora de restriccion, se bajo  a 1
> Bajar restriccion da 1 hora

- package.json
- src/App.js
> Develop to main

- src/components/boookAppointment.js
Reverts hamalsolutions/little-belies-widget#134
> Revert "ipAdress"

- src/components/boookAppointment.js
Reverts hamalsolutions/little-belies-widget#135
> Revert "Revert "ipAdress""
